### ISSUE TITLE
'POST /tipjars/' is_public이랑 is_available 설명 좀

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#11]
@june2 
1. is_public이 아래 이미지에서 '기부자의 기부금액 공개여부' 인 거 같은데, 맞나요?
저 기능은 필요 없는 거 같습니다. 항상 공개입니다.

2. is_available 대신 status 쓰는 거죠? 
아니라면 status와 is_available의 관계나 업데이트는 어떤 상황에 어떻게 되나요?

![image](https://user-images.githubusercontent.com/3310008/76627593-a1058680-657e-11ea-8417-f850e00191fd.png)

**Comment by june2** [comment]
- is_available 삭제했습니다. 
아래 참조해주세요.
https://github.com/ESC2020/tipjar-donee-api/issues/6#issuecomment-596614113
