### ISSUE TITLE
'GET /tipjars/{id}' 없는 id 에러

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#16]
@june2 
id를 없는 것으로 리퀘스트 보내면
404 Not Found 가 아니라 401 에러가 발생합니다.

[https://en.wikipedia.org/wiki/List_of_HTTP_status_codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**Comment by june2** [comment]
@dustnote
완료
