### ISSUE TITLE
'GET /files/signedUrl' 아직 구현 안된 듯

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#2]
parameters 두 가지 보내고 리턴 받을 수 있게 해주세요.
ex) filename=abc.png
       filetype=image/png

**Comment by june2** [comment]
https://gyuha.tistory.com/511

**Comment by june2** [comment]
아래처럼 res 하면 될까요?
```
{
s3Link: 'http~~~',
filename: 'abc.png',
filetype='image/png'
}
```

**Comment by dustnote** [comment]
@june2 
내용이 잘 못 전달된 거 같은데, GET request 보낼 때 querystring 으로 filename이랑 filetype을 보낸다는 얘기였어요.
response는 지금처럼 signed url 보내줘도 될 것 같아요.

**Comment by june2** [comment]
- auth api 로 통합할게요. 아래 이슈확인해주세요.
https://github.com/ESC2020/tipjar-auth/issues/1#issuecomment-596201726
