### ISSUE TITLE
파일 업로드가 따로 있는 이유가 궁금합니다.

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#3]
현재 Donee API 에만 있는데, Donor API 에도 GET /files/signedUrl로 생기나요?
따로 생기면 s3에 key 다르게 해서, 크게 donees랑 donors 구분해서 저장되게 하려는 게 맞죠?

**Comment by june2** [comment]
- 구분할까요?
- auth쪽에 업로드 api 통합으로 해놓을까요??

**Comment by dustnote** [comment]
@june2 
s3에서 key 별 권한 따로 부여할 게 아니고, 프로필 이미지 처럼 공개되는 리소스이니까 합쳐도 될 것 같습니다.
단, development나 staging, production 등은 분리되서 저장되야 될 것 같아요.

**Comment by june2** [comment]
- auth api 로 통합할게요. 아래 이슈확인해주세요.
https://github.com/ESC2020/tipjar-auth/issues/1#issuecomment-596201726
