### ISSUE TITLE
'GET /tipjars/' response 중 property 'data' 이름 변경 요청

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#4]
@june2 
response에 data, total, page, hasNext 오는데,
data만 results로 변경해줘요.
큰 이슈는 아니지만 부탁해요

**Comment by june2** [comment]
변경 완료요
![image](https://user-images.githubusercontent.com/5827617/76218639-e9a80180-6257-11ea-9c4c-6e76a6b57386.png)
