### ISSUE TITLE
'GET /tipjars/' 팁자 모델 확인

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#5]
@june2 
아래 11번을 보면 팁자 타입이 다음과 같이 있는데, 그에 대한 property는 없네요? 확인 부탁해요.
그리고 하나 더. 팁자 id 1은 mandatory 이어야 하는데 goal_coin, goal_participate 값이 설정되어 있네요?
아래 그림에서 기본은 모금목표가 없어야 하는데 잘못 되어 있네요.
그리고 하나 더 현재 총 모금액은 total_coin으로 확인 가능한데, 총 기부자 수는 없네요?

- 기본: mandatory(기본으로 생기는 팁자. 삭제불가, 제한사항X)
- 일반: normal

![image](https://user-images.githubusercontent.com/3310008/76225753-4ad3d300-6260-11ea-95e1-1c9fe8b8b9af.png)

**Comment by june2** [comment]
![image](https://user-images.githubusercontent.com/5827617/76281957-b27a3480-62d9-11ea-9950-3993f8eba542.png)

- 아래 11번을 보면 팁자 타입이 다음과 같이 있는데, 그에 대한 property는 없네요? 확인 부탁해요.
   - type, status 변경했어요. 자세한 사항 아래 링크 확인해주세요.
   - https://github.com/ESC2020/tipjar-donee-api/issues/6#issuecomment-596614113

- 그리고 하나 더. 팁자 id 1은 mandatory 이어야 하는데 goal_coin, goal_participate 값이 설정되어 있네요?
   - 처리했습니다.

- 그리고 하나 더 현재 총 모금액은 total_coin으로 확인 가능한데, 총 기부자 수는 없네요?
   - 처리했습니다.

----
mandatory 팁자 관련해서 
   - 현재는 donee생성(신청)시 자동으로 mandatory 팁자생성되게 했습니다. 
   - 추후에 donee신청하면 관리자에서 승인시, mandatory 팁자생성 되게 바꿀계획입니다.

**Comment by dustnote** [comment]
@june2 
굿. 확인하고 이슈 클로우즈 할께요.
