### ISSUE TITLE
'GET /tipjars/' 팁자 상태 choices

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#6]
@june2 
status가 RUN으로만 확인되는데 value choices 랑 설명 좀 해주세요.
DB 모델링 한 문서에 이 설명도 있나요? 모델링 문서 찾을 수 없는데 링크 좀 공유해 주세요.

**Comment by june2** [comment]
- 일단 제가 임의 만들어놓은 필드에요. 같이 말하면서 정해야될거같에요. 
- ERD는 업데이트를 좀해야되요, https://github.com/ESC2020/tipjar-typeorm/issues/1

- 일단 생각했던거 정리햇어요, 필요한 상태값 더 있으면 추가해주세요.
enum : status =   [RUN, END]
- RUN : 모금중 (default)
- END :  모금종료

**Comment by dustnote** [comment]
@june2 
생각나는 상태들 전부 나열하면 아래 정도 되는 거 같아요.
전부 적용할지, 특정 조건으로 frontend에서 처리해 할지 의견 주세요.
사용자(donee, donor)한테 오역될 여지가 있는지도 의견 주세요.
donee 는 donor한테 노출되지 않은 tipjar도 다 볼 수 있으니까 상태구분이 좀 디테일하게 필요할 거 같아요.

- STANDBY : 모금 대기. 생성은 되었으나 시작날짜가 아직 안된 상태.
- ONGOING: 모금 중.
- ENDED: 모금종료.
- SUSPENDED: 모금 중지. 정책위반이나 특정이슈로 인해서 중지된 상태.

**Comment by june2** [comment]
![image](https://user-images.githubusercontent.com/5827617/76231302-64791880-6268-11ea-9479-4362f4c3ffcc.png)

- STANDBY/ONGOING/ENDED  을 날짜로 체크하려면 프론트에서  start_at/end_at 값으로 활용해서 해야될거 같에요. 

-----
is_available 필드 삭제하고 status에 아래처럼 관리 하면 어떨가요.?
- ACTIVE (활성, default)
   - ACTIVE일시, start_at/end_at 계산하여   -> STANDBY/ONGOING/ENDED 표시 
- INACTIVE (비활성,  donee 가 설정)
- SUSPENDED (모금 중지. 정책위반이나 특정이슈로 인해서 중지된 상태, 관리자 설정) 

---
도니가 팁자 조회시 모두 조회
도너가 팁자 조회시 status가 ACTIVE인 상태만 노출.

**Comment by dustnote** [comment]
@june2 
네. 이렇게 가시지요.
front-end 쪽 개발 반영하고 제가 이슈 닫을께요.
