### ISSUE TITLE
'/tipjars/' 에서 goal_participant, total_participant 이슈

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-donee-api#8]
@june2 
1. 먼저 naming을 각각 goal_donors, total_donors로 하는 것이 어떤지요?
다른 모델이랑 연결되서 연상되도록.
추가로 goal_coin과 total_coin도 goal_coins, total_coins 가 좋아 보입니다.
이런 류의 필드는 앞으로 복수형으로 가는 게 좋다고 생각합니다.

2. total_participant의 카운팅이 어떻게 되나요?
donor A가 처음 기부를 하고 이후에 다시 한 번 기부를 하면 또 +1이 되나요?
그것보다는 기부 발생 횟수가 아닌 기부자 수였으면 합니다.
여러 번 기부는 가능합니다.

3. total_participant가 다른 것들과 다르게 "0"으로 string으로 오고 있습니다.
확인 부탁드려요.

**Comment by june2** [comment]
![image](https://user-images.githubusercontent.com/5827617/76321148-f21a3e00-6324-11ea-9bae-4b3d83e4f166.png)

- 1,3 처리됬습니다.
- 2 donor_id로 카운트 됩니다. (기부자 수)
